package org.openboxes.location.enums;

import java.util.List;

public enum SupportedActivitiesEnum {
    MANAGE_INVENTORY, ADJUST_INVENTORY, APPROVE_ORDER, APPROVE_REQUEST,
    PLACE_ORDER, PLACE_REQUEST, FULFILL_ORDER, FULFILL_REQUEST,
    SEND_STOCK, RECEIVE_STOCK, CONSUME_STOCK,
    CROSS_DOCKING, PUTAWAY_STOCK, PICK_STOCK,
    EXTERNAL,
    ENABLE_NOTIFICATIONS, ENABLE_WEBHOOKS,
    ENABLE_REQUESTOR_APPROVAL_NOTIFICATIONS, ENABLE_FULFILLER_APPROVAL_NOTIFICATIONS,
    PACK_SHIPMENT, PARTIAL_RECEIVING,
    REQUIRE_ACCOUNTING, ENABLE_CENTRAL_PURCHASING,
    HOLD_STOCK, SUBMIT_REQUEST, DYNAMIC_CREATION,
    AUTOSAVE, ALLOW_OVERPICK, CYCLE_COUNT,
    NONE;

    public static List<String> list() {
        return java.util.Arrays.stream(values()).map(Enum::name).toList();
    }
}
